### ISSUE TITLE
W Repo

### ISSUE THREAD

**Issue by Pr0t0ns** [kekeds/auto-header-format#2]
Thank god someone made this I’m tired of always formatting the headers

**Comment by CodeByAidan** [comment]
shut up yung blud, please close this issue. don't leave complements as an issue, let alone an OPEN issue.

**Comment by Pr0t0ns** [comment]
> shut up yung blud, please close this issue. don't leave complements as an issue, let alone an OPEN issue.

Okay Github Moderator, I'll close it now. 34k+ commits and still a nn that's sad,  feel free to hmu i'll help you make some good repos.

**Comment by CodeByAidan** [comment]
I make papers, I work as a freelancer, I make coding projects and pursue them. Sorry I don't entice you, but I do have my own audience.

**Comment by Pr0t0ns** [comment]
> I make papers, I work as a freelancer, I make coding projects and pursue them. Sorry I don't entice you, but I do have my own audience.

How are you a freelancer, you can't code properly fix your fork your missing context properties :)

**Comment by CodeByAidan** [comment]
> > I make papers, I work as a freelancer, I make coding projects and pursue them. Sorry I don't entice you, but I do have my own audience.
> 
> How are you a freelancer, you can't code properly fix your fork your missing context properties :)

Hahaha, feel free to contribute if you want to add-on!

**Comment by Pr0t0ns** [comment]
> > > I make papers, I work as a freelancer, I make coding projects and pursue them. Sorry I don't entice you, but I do have my own audience.
> > 
> > 
> > How are you a freelancer, you can't code properly fix your fork your missing context properties :)
> 
> Hahaha, feel free to contribute if you want to add-on!

Sure, I might make a pr soon.
